//! 平台服务管理文件生成
//!
//! 为 `easybot --init` 提供各平台的服务配置文件和管理脚本生成能力。
//! 通过 `cfg!(target_os)` 在运行时检测当前平台，只生成对应的文件。
//!
//! ## 各平台产出
//!
//! | 平台 | 配置文件 | 管理脚本 | 服务管理器 |
//! |------|---------|---------|-----------|
//! | Linux | `easybot.service` | `easybot.sh` | systemd |
//! | macOS | `com.easybot.gateway.plist` | `easybot.sh` | launchd |
//! | Windows | —（脚本内嵌） | `manage-service.ps1` | sc.exe |

use super::home::EasyBotPaths;
use std::path::PathBuf;

/// 生成当前平台的所有服务管理文件。
///
/// 仅在 `--init` 时调用。返回 `Vec<(路径, 文件内容)>`，调用方负责写入磁盘。
pub fn generate_service_files(paths: &EasyBotPaths) -> Vec<(PathBuf, String)> {
    let mut files: Vec<(PathBuf, String)> = Vec::new();

    if cfg!(target_os = "linux") {
        files.push((
            paths.home.join("easybot.service"),
            generate_systemd_unit(paths),
        ));
        files.push((paths.home.join("easybot.sh"), generate_linux_script(paths)));
    } else if cfg!(target_os = "macos") {
        files.push((
            paths.home.join("com.easybot.gateway.plist"),
            generate_launchd_plist(paths),
        ));
        files.push((paths.home.join("easybot.sh"), generate_macos_script(paths)));
    } else if cfg!(target_os = "windows") {
        files.push((
            paths.home.join("manage-service.ps1"),
            generate_windows_script(paths),
        ));
    }

    files
}

// ──────────────────────────────────────
// Linux: systemd service unit
// ──────────────────────────────────────

fn generate_systemd_unit(paths: &EasyBotPaths) -> String {
    let bin_path = current_exe_fallback();
    let home = paths.home.display();
    let config = paths.config_file.display();
    let env = paths.env_path.display();
    let svc_path_buf = paths.home.join("easybot.service");
    let svc_path = svc_path_buf.display();

    format!(
        r#"# EasyBot systemd service unit
# Generated by `easybot --init`
#
# Install:
#   sudo cp {svc} /etc/systemd/system/easybot.service
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now easybot
#
# Manage:
#   ./easybot.sh install|uninstall|start|stop|restart|status|enable|disable|logs

[Unit]
Description=EasyBot - IM Gateway Service
Documentation=https://github.com/EasyIndie/EasyBot
After=network.target
Wants=network.target

[Service]
Type=simple
User=easybot
Group=easybot
WorkingDirectory={home}
ExecStart={bin} --config {cfg}
Restart=on-failure
RestartSec=5s
StartLimitInterval=10s
StartLimitBurst=5
EnvironmentFile=-{env}
StandardOutput=journal
StandardError=journal
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
CapabilityBoundingSet=

[Install]
WantedBy=multi-user.target
"#,
        svc = svc_path,
        home = home,
        bin = bin_path,
        cfg = config,
        env = env,
    )
}

// ──────────────────────────────────────
// macOS: launchd plist
// ──────────────────────────────────────

fn generate_launchd_plist(paths: &EasyBotPaths) -> String {
    let bin_path = current_exe_fallback();
    let home = paths.home.display();
    let config = paths.config_file.display();

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.easybot.gateway</string>

    <key>ProgramArguments</key>
    <array>
        <string>{bin}</string>
        <string>--config</string>
        <string>{cfg}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>{home}</string>

    <key>KeepAlive</key>
    <true/>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>{home}/logs/stdout.log</string>

    <key>StandardErrorPath</key>
    <string>{home}/logs/stderr.log</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>EASYBOT_HOME</key>
        <string>{home}</string>
    </dict>
</dict>
</plist>
"#,
        bin = bin_path,
        cfg = config,
        home = home,
    )
}

// ──────────────────────────────────────
// Linux: systemd management script
// ──────────────────────────────────────

fn generate_linux_script(paths: &EasyBotPaths) -> String {
    let home = paths.home.display();
    let svc_buf = paths.home.join("easybot.service");
    let svc_src = svc_buf.display();
    let svc_dest = "/etc/systemd/system/easybot.service".to_string();
    let embedded_bin = current_exe_fallback();
    let config_path = paths.config_file.display();

    format!(
        r#"#!/usr/bin/env bash
# EasyBot service management script (Linux / systemd)
# Generated by `easybot --init`
set -euo pipefail

EASYBOT_HOME="{home}"
SERVICE_NAME="easybot"
SERVICE_SRC="{svc_src}"
SERVICE_DEST="{svc_dest}"
CONFIG="{config}"
EMBEDDED_BIN="{bin}"

# 自动检测二进制路径：嵌入路径 → PATH → 脚本同目录
find_binary() {{
    if [ -x "$EMBEDDED_BIN" ]; then
        echo "$EMBEDDED_BIN"
    elif command -v easybot &>/dev/null; then
        echo "$(command -v easybot)"
    elif [ -x "$(dirname "$0")/easybot" ]; then
        echo "$(dirname "$0")/easybot"
    else
        echo "$EMBEDDED_BIN"  # 回退，让 systemd 报错时路径可见
    fi
}}

# 安装服务，自动修正路径
install_service() {{
    local bin
    bin=$(find_binary)
    echo "→ 二进制路径: $bin"
    if [ "$bin" != "$EMBEDDED_BIN" ]; then
        echo "  (检测到路径与生成时不一致，已自动修正)"
        sed "s|ExecStart=.*|ExecStart=${bin} --config ${{CONFIG}}|" "$SERVICE_SRC" > /tmp/easybot.service
        sudo cp /tmp/easybot.service "$SERVICE_DEST"
        rm -f /tmp/easybot.service
    else
        sudo cp "$SERVICE_SRC" "$SERVICE_DEST"
    fi
    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME"
    sudo systemctl start "$SERVICE_NAME"
    echo "✓ EasyBot 服务已安装并启动"
    echo "  状态: systemctl status $SERVICE_NAME"
    echo "  日志: journalctl -u $SERVICE_NAME -f"
}}

usage() {{
    cat <<EOF
Usage: $(basename "$0") {{install|uninstall|start|stop|restart|status|enable|disable|logs}}

Commands:
  install    安装并启动 systemd 服务（需 sudo）
  uninstall  停止并卸载 systemd 服务（需 sudo）
  start      启动服务（需 sudo）
  stop       停止服务（需 sudo）
  restart    重启服务（需 sudo）
  status     查看服务状态
  enable     设置开机自启（需 sudo）
  disable    取消开机自启（需 sudo）
  logs       查看实时日志
EOF
    exit 0
}}

case "${{1:-help}}" in
    install)
        install_service
        ;;
    uninstall)
        echo "→ 卸载 EasyBot systemd 服务..."
        sudo systemctl stop "$SERVICE_NAME" 2>/dev/null || true
        sudo systemctl disable "$SERVICE_NAME" 2>/dev/null || true
        sudo rm -f "$SERVICE_DEST"
        sudo systemctl daemon-reload
        echo "✓ EasyBot 服务已卸载"
        ;;
    start)
        sudo systemctl start "$SERVICE_NAME"
        echo "✓ 服务已启动"
        ;;
    stop)
        sudo systemctl stop "$SERVICE_NAME"
        echo "✓ 服务已停止"
        ;;
    restart)
        sudo systemctl restart "$SERVICE_NAME"
        echo "✓ 服务已重启"
        ;;
    status)
        systemctl status "$SERVICE_NAME" --no-pager
        ;;
    enable)
        sudo systemctl enable "$SERVICE_NAME"
        echo "✓ 已设置开机自启"
        ;;
    disable)
        sudo systemctl disable "$SERVICE_NAME"
        echo "✓ 已取消开机自启"
        ;;
    logs)
        journalctl -u "$SERVICE_NAME" -n 50 -f
        ;;
    help|--help|-h)
        usage
        ;;
    *)
        echo "未知命令: $1"
        usage
        ;;
esac
"#,
        home = home,
        svc_src = svc_src,
        svc_dest = svc_dest,
        config = config_path,
        bin = embedded_bin,
    )
}

// ──────────────────────────────────────
// macOS: launchd management script
// ──────────────────────────────────────

fn generate_macos_script(paths: &EasyBotPaths) -> String {
    let home = paths.home.display();
    let plist_name = "com.easybot.gateway.plist".to_string();
    let plist_buf = paths.home.join(&plist_name);
    let plist_src = plist_buf.display();
    let plist_dest = format!("$HOME/Library/LaunchAgents/{}", plist_name);
    let service_label = "com.easybot.gateway".to_string();
    let embedded_bin = current_exe_fallback();
    let config_path = paths.config_file.display();

    format!(
        r#"#!/usr/bin/env bash
# EasyBot service management script (macOS / launchd)
# Generated by `easybot --init`
set -euo pipefail

EASYBOT_HOME="{home}"
PLIST_SRC="{plist_src}"
PLIST_DEST="{plist_dest}"
SERVICE_LABEL="{label}"
CONFIG="{config}"
EMBEDDED_BIN="{bin}"

# 自动检测二进制路径：嵌入路径 → PATH → 脚本同目录
find_binary() {{
    if [ -x "$EMBEDDED_BIN" ]; then
        echo "$EMBEDDED_BIN"
    elif command -v easybot &>/dev/null; then
        echo "$(command -v easybot)"
    elif [ -x "$(dirname "$0")/easybot" ]; then
        echo "$(dirname "$0")/easybot"
    else
        echo "$EMBEDDED_BIN"  # 回退
    fi
}}

# 安装服务，自动修正路径
install_service() {{
    local bin
    bin=$(find_binary)
    echo "→ 二进制路径: $bin"
    if [ "$bin" != "$EMBEDDED_BIN" ]; then
        echo "  (检测到路径与生成时不一致，已自动修正)"
        /usr/libexec/PlistBuddy -c "Set :ProgramArguments:0 $bin" "$PLIST_SRC" 2>/dev/null || true
    fi
    cp "$PLIST_SRC" "$PLIST_DEST"
    launchctl load -w "$PLIST_DEST"
    echo "✓ EasyBot 服务已安装并启动"
    echo "  状态: launchctl list $SERVICE_LABEL"
    echo "  日志: log show --predicate 'process=\"easybot\"' --last 1h"
}}

usage() {{
    cat <<EOF
Usage: $(basename "$0") {{install|uninstall|start|stop|restart|status|enable|disable|logs}}

Commands:
  install    安装并启动 launchd 服务
  uninstall  停止并卸载 launchd 服务
  start      启动服务
  stop       停止服务
  restart    重启服务（unload + load）
  status     查看服务状态
  enable     加载 plist（设置开机自启）
  disable    卸载 plist（取消开机自启）
  logs       查看最近日志
EOF
    exit 0
}}

case "${{1:-help}}" in
    install)
        install_service
        ;;
    uninstall)
        echo "→ 卸载 EasyBot launchd 服务..."
        launchctl stop "$SERVICE_LABEL" 2>/dev/null || true
        launchctl unload -w "$PLIST_DEST" 2>/dev/null || true
        rm -f "$PLIST_DEST"
        echo "✓ EasyBot 服务已卸载"
        ;;
    start)
        launchctl start "$SERVICE_LABEL"
        echo "✓ 服务已启动"
        ;;
    stop)
        launchctl stop "$SERVICE_LABEL"
        echo "✓ 服务已停止"
        ;;
    restart)
        echo "→ 重启服务..."
        launchctl unload "$PLIST_DEST" 2>/dev/null || true
        sleep 1
        launchctl load -w "$PLIST_DEST"
        echo "✓ 服务已重启"
        ;;
    status)
        launchctl list "$SERVICE_LABEL"
        ;;
    enable)
        launchctl load -w "$PLIST_DEST"
        echo "✓ 已设置开机自启"
        ;;
    disable)
        launchctl unload -w "$PLIST_DEST"
        echo "✓ 已取消开机自启"
        ;;
    logs)
        log show --predicate 'process="easybot"' --last 1h
        ;;
    help|--help|-h)
        usage
        ;;
    *)
        echo "未知命令: $1"
        usage
        ;;
esac
"#,
        home = home,
        plist_src = plist_src,
        plist_dest = plist_dest,
        label = service_label,
        config = config_path,
        bin = embedded_bin,
    )
}

// ──────────────────────────────────────
// Windows: PowerShell management script
// ──────────────────────────────────────

fn generate_windows_script(paths: &EasyBotPaths) -> String {
    let bin_path = current_exe_fallback();
    let config = paths.config_file.display().to_string();
    let home = paths.home.display().to_string();
    let log_path = paths.logs_dir.join("easybot.log").display().to_string();

    format!(
        r#"<#
.SYNOPSIS
    EasyBot Windows 服务管理脚本
.DESCRIPTION
    使用 sc.exe 管理 EasyBot Windows 服务，提供完整的服务生命周期管理。
    需要以管理员权限运行。
    Generated by `easybot --init`
#>

param(
    [Parameter(Position=0)]
    [string]$Command = "help"
)

$ServiceName = "EasyBot"
$ConfigPath = "{cfg}"
$LogPath = "{log}"
$Home = "{home}"
$EmbeddedBin = "{bin}"

# 自动检测二进制路径：嵌入路径 → PATH → 脚本同目录
function Find-Binary {{
    if (Test-Path $EmbeddedBin) {{ return $EmbeddedBin }}
    $fromPath = Get-Command "easybot.exe" -ErrorAction SilentlyContinue
    if ($fromPath) {{ return $fromPath.Source }}
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $localBin = Join-Path $scriptDir "easybot.exe"
    if (Test-Path $localBin) {{ return $localBin }}
    return $EmbeddedBin  # 回退
}}

function Show-Usage {{
    Write-Host @"
用法: $(Split-Path -Leaf $MyInvocation.MyCommand.Path) {{install|uninstall|start|stop|restart|status|enable|disable|logs}}

Commands:
  install    安装并启动 Windows 服务（需要管理员权限）
  uninstall  停止并卸载 Windows 服务（需要管理员权限）
  start      启动服务
  stop       停止服务
  restart    重启服务
  status     查看服务状态
  enable     设置开机自启
  disable    取消开机自启
  logs       查看实时日志
"@
}}

function Test-Admin {{
    $identity = [Security.Principal.WindowsPrincipal]::new(
        [Security.Principal.WindowsIdentity]::GetCurrent()
    )
    return $identity.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}}

switch ($Command.ToLower()) {{
    "install" {{
        if (-not (Test-Admin)) {{
            Write-Warning "安装服务需要管理员权限，请以管理员身份运行 PowerShell"
            exit 1
        }}
        $bin = Find-Binary
        Write-Host "→ 二进制路径: $bin"
        if ($bin -ne $EmbeddedBin) {{
            Write-Host "  (检测到路径与生成时不一致，已自动修正)"
        }}
        sc.exe create $ServiceName binPath="`"$bin`" --config `"$ConfigPath`"" start=auto
        sc.exe failure $ServiceName reset=0 actions=restart/5000/restart/10000/""/60000
        Start-Service $ServiceName
        Write-Host "✓ EasyBot 服务已安装并启动"
        Write-Host "  状态: Get-Service $ServiceName"
        Write-Host "  日志: Get-Content -Tail 50 -Wait `"$LogPath`""
    }}
    "uninstall" {{
        if (-not (Test-Admin)) {{
            Write-Warning "卸载服务需要管理员权限，请以管理员身份运行 PowerShell"
            exit 1
        }}
        Write-Host "→ 卸载 EasyBot Windows 服务..."
        Stop-Service $ServiceName -ErrorAction SilentlyContinue
        sc.exe delete $ServiceName
        Write-Host "✓ EasyBot 服务已卸载"
    }}
    "start" {{
        Start-Service $ServiceName
        Write-Host "✓ 服务已启动"
    }}
    "stop" {{
        Stop-Service $ServiceName
        Write-Host "✓ 服务已停止"
    }}
    "restart" {{
        Restart-Service $ServiceName
        Write-Host "✓ 服务已重启"
    }}
    "status" {{
        try {{
            $svc = Get-Service $ServiceName -ErrorAction Stop
            $svc | Select-Object Name, Status, StartType
        }} catch {{
            Write-Warning "服务 '$ServiceName' 不存在"
        }}
    }}
    "enable" {{
        sc.exe config $ServiceName start=auto
        Write-Host "✓ 已设置开机自启"
    }}
    "disable" {{
        sc.exe config $ServiceName start=demand
        Write-Host "✓ 已取消开机自启"
    }}
    "logs" {{
        if (Test-Path $LogPath) {{
            Get-Content $LogPath -Tail 50 -Wait
        }} else {{
            Write-Warning "日志文件不存在: $LogPath"
        }}
    }}
    default {{
        Show-Usage
    }}
}}
"#,
        bin = bin_path,
        cfg = config,
        log = log_path,
        home = home,
    )
}

// ──────────────────────────────────────
// 辅助函数
// ──────────────────────────────────────

/// 获取当前二进制路径，失败时回退到平台默认路径
fn current_exe_fallback() -> String {
    std::env::current_exe()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| {
            if cfg!(target_os = "windows") {
                "C:\\Program Files\\EasyBot\\easybot.exe".to_string()
            } else {
                "/usr/local/bin/easybot".to_string()
            }
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    /// 每个测试使用独立的临时目录（PID 确保进程间不冲突）
    fn test_paths() -> EasyBotPaths {
        let dir = env::temp_dir().join(format!(
            "easybot_svc_test_{}_{}",
            std::process::id(),
            // 使用简单计数器区分同一进程内的测试
            (std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
                % 1000000)
        ));
        let _ = std::fs::create_dir_all(&dir);
        EasyBotPaths::new(dir).unwrap()
    }

    #[test]
    fn test_generate_systemd_unit_contains_required_sections() {
        let paths = test_paths();
        let content = generate_systemd_unit(&paths);
        assert!(content.contains("[Unit]"), "missing [Unit]");
        assert!(content.contains("[Service]"), "missing [Service]");
        assert!(content.contains("[Install]"), "missing [Install]");
        assert!(
            content.contains("Restart=on-failure"),
            "missing Restart=on-failure"
        );
        assert!(
            content.contains("WantedBy=multi-user.target"),
            "missing WantedBy"
        );
        assert!(content.contains("Type=simple"), "missing Type=simple");
        assert!(
            content.contains(&paths.home.to_string_lossy().to_string()),
            "missing home path"
        );
        assert!(content.contains("gateway.yaml"), "missing config reference");
    }

    #[test]
    fn test_generate_launchd_plist_contains_required_keys() {
        let paths = test_paths();
        let content = generate_launchd_plist(&paths);
        assert!(content.contains("com.easybot.gateway"), "missing label");
        assert!(
            content.contains("<key>KeepAlive</key>"),
            "missing KeepAlive"
        );
        assert!(
            content.contains("<key>RunAtLoad</key>"),
            "missing RunAtLoad"
        );
        assert!(
            content.contains("<key>ProgramArguments</key>"),
            "missing ProgramArguments"
        );
        assert!(
            content.contains("<key>StandardOutPath</key>"),
            "missing stdout"
        );
        assert!(
            content.contains("<key>StandardErrorPath</key>"),
            "missing stderr"
        );
        assert!(content.contains("gateway.yaml"), "missing config reference");
    }

    #[test]
    fn test_generate_linux_script_contains_commands() {
        let paths = test_paths();
        let content = generate_linux_script(&paths);
        let required = &[
            "install",
            "uninstall",
            "start",
            "stop",
            "restart",
            "status",
            "enable",
            "disable",
            "logs",
        ];
        for cmd in required {
            assert!(content.contains(cmd), "missing command: {}", cmd);
        }
        assert!(content.contains("systemctl"), "missing systemctl");
        assert!(content.contains("sudo"), "missing sudo");
        assert!(
            content.contains(&paths.home.to_string_lossy().to_string()),
            "missing home path"
        );
    }

    #[test]
    fn test_generate_macos_script_contains_commands() {
        let paths = test_paths();
        let content = generate_macos_script(&paths);
        let required = &[
            "install",
            "uninstall",
            "start",
            "stop",
            "restart",
            "status",
            "enable",
            "disable",
            "logs",
        ];
        for cmd in required {
            assert!(content.contains(cmd), "missing command: {}", cmd);
        }
        assert!(content.contains("launchctl"), "missing launchctl");
        assert!(
            content.contains("com.easybot.gateway"),
            "missing service label"
        );
        assert!(
            content.contains(&paths.home.to_string_lossy().to_string()),
            "missing home path"
        );
    }

    #[test]
    fn test_generate_windows_script_contains_commands() {
        let paths = test_paths();
        let content = generate_windows_script(&paths);
        let required = &[
            "install",
            "uninstall",
            "start",
            "stop",
            "restart",
            "status",
            "enable",
            "disable",
            "logs",
        ];
        for cmd in required {
            assert!(content.contains(cmd), "missing command: {}", cmd);
        }
        assert!(content.contains("sc.exe"), "missing sc.exe");
        assert!(content.contains("Start-Service"), "missing Start-Service");
        assert!(
            content.contains("Restart-Service"),
            "missing Restart-Service"
        );
        assert!(content.contains("Get-Service"), "missing Get-Service");
        assert!(content.contains("--config"), "missing --config flag");
    }

    #[test]
    fn test_generate_service_files_returns_platform_files() {
        let paths = test_paths();
        let files = generate_service_files(&paths);

        if cfg!(target_os = "linux") {
            assert!(files.iter().any(|(p, _)| p.ends_with("easybot.service")));
            assert!(files.iter().any(|(p, _)| p.ends_with("easybot.sh")));
            assert_eq!(files.len(), 2);
        } else if cfg!(target_os = "macos") {
            assert!(
                files
                    .iter()
                    .any(|(p, _)| p.ends_with("com.easybot.gateway.plist"))
            );
            assert!(files.iter().any(|(p, _)| p.ends_with("easybot.sh")));
            assert_eq!(files.len(), 2);
        } else if cfg!(target_os = "windows") {
            assert!(files.iter().any(|(p, _)| p.ends_with("manage-service.ps1")));
            assert_eq!(files.len(), 1);
        } else {
            assert_eq!(files.len(), 0);
        }
    }
}
